# File : .pep8speaks.yml
scanner:
    diff_only: False


pycodestyle:
    max-line-length: 120
    ignore:
        - E402  # module level import not at top of file

only_mention_files_with_errors: True
